name: Demo Commit Sign Dispatch GitHub Actions Workflow

on:  
  workflow_dispatch:

jobs:
  sign-verify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Loop through source files 
        run: |
          # Define the directory to loop through
          TARGET_DIR="./HelloWorld/src/com/example/helloworld" 
          SCRIPTS_DIR="./scripts"

          # Loop through each file in the target directory
          for file in "$TARGET_DIR"/*; do
            if [ -f "$file" ]; then # Check if it's a regular file
              echo "Processing file: $file"
              curl -F "workerName=OpenPGPSigner" -F "file=@$file" ${{secrets.SIGNSERVER_URL}} > "$file.asc"
              ls -al $TARGET_DIR
              echo "PWD = "
              pwd
              cat "$file.asc"
              cat "$file"
              ls -al $SCRIPTS_DIR
              $SCRIPTS_DIR/pgp-verify.sh "$file.asc" "$file"
            fi
          done

          echo "List workspace..."
          ls -al ${{github.workspace}}

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: signed-artifacts
          path: |
            ${{github.workspace}}/*.java 
            ${{github.workspace}}/*.asc 

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          name: signed-artifacts
          path: |
            ./dowloaded-signed-artifacts          
   
      - name: List
        run: ls -al 
