name: Demo Commit PGP GitHub Actions Workflow

on:  
  workflow_dispatch:

jobs:
  process_files:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Import PGP Public Key
        run: |
          echo ${{secrets.PGP_PUBLIC_KEY}} | gpg --import

      - name: Loop through files in a directory
        run: |
          # Define the directory to loop through
          TARGET_DIR="./HelloWorld/src/com/example/helloworld" 

          # Loop through each file in the target directory
          for file in "$TARGET_DIR"/*; do
            if [ -f "$file" ]; then # Check if it's a regular file
              echo "Processing file: $file"
              curl -F "workerName=OpenPGPSigner" -F "file=@$file" ${{secrets.SIGNSERVER_URL}} > "$file.asc"
              ls -al 
              cat "$file.asc"
              cat "$file"
              # gpg --verify "$file.asc" "$file"
            fi
          done

  verify:
    runs-on: ubuntu-latest # The type of runner that the job will run on
    needs: process_files 
    steps:

    - name: Decode Root CA Certificate
      env:
        ROOT_CERT_B64: ${{secrets.ROOT_CA_BASE64}} # Store your base64 encoded certificate in GitHub Secrets
      run: |
        echo "$ROOT_CERT_B64" | base64 --decode > root_ca.cer

    - name: Decode Intermediate CA Certificate
      env:
        INTERMEDIATE_CERT_B64: ${{secrets.INTERMEDIATE_CA_BASE64}} # Store your base64 encoded certificate in GitHub Secrets
      run: |
        echo "$INTERMEDIATE_CERT_B64" | base64 --decode > intermediate_ca.cer

    - name: Import Root CA Certificate into Keystore
      run: |
        keytool -import -alias myrootcacert -file root_ca.cer -keystore truststore.jks -storepass changeit -noprompt

    - name: Import Intermediate CA Certificate into Keystore
      run: |
        keytool -import -alias myintermediatecacert -file intermediate_ca.cer -keystore truststore.jks -storepass ${{secrets.JKS_STOREPASS}} -noprompt

    - name: List base signed dir 
      run: ls -al *

    - name: List workspace signed dir 
      run: ls -al ${{github.workspace}}/*
