name: Demo Commit PGP GitHub Actions Workflow

on:  
  workflow-dispatch:

jobs:
  get_file_list:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./HelloWorld/src/com/example/helloworld
    outputs:
      files: ${{ steps.get_files.outputs.files }}
    steps:
      - uses: actions/checkout@v4
      - name: Get all tracked files
        id: get_files
        run: echo "::set-output name=files::$(git ls-files)"

  process_individual_files:
    runs-on: ubuntu-latest
    needs: get_file_list
    steps:
      - uses: actions/checkout@v4
      #- name: Make script executable (if it's a shell script)
      #  run: chmod +x ./scripts/pgp-signer.sh # Grants execute permissions to the script
      - name: Process files using bash loop
        run: |
          IFS=$'\n' read -d '' -r -a files <<< "${{ needs.get_file_list.outputs.files }}"
          for file in "${files[@]}"; do
            echo "Processing file: $file"
            # ./scripts/pgp-signer.sh "$file" ${{secrets.SIGNSERVER_URL}}
          done
        shell: bash

      - name: List files
        run: ls -al .

  verify:
    runs-on: ubuntu-latest # The type of runner that the job will run on
    needs: process_individual_files 
    steps:

    - name: Decode Root CA Certificate
      env:
        ROOT_CERT_B64: ${{secrets.ROOT_CA_BASE64}} # Store your base64 encoded certificate in GitHub Secrets
      run: |
        echo "$ROOT_CERT_B64" | base64 --decode > root_ca.cer

    - name: Decode Intermediate CA Certificate
      env:
        INTERMEDIATE_CERT_B64: ${{secrets.INTERMEDIATE_CA_BASE64}} # Store your base64 encoded certificate in GitHub Secrets
      run: |
        echo "$INTERMEDIATE_CERT_B64" | base64 --decode > intermediate_ca.cer

    - name: Import Root CA Certificate into Keystore
      run: |
        keytool -import -alias myrootcacert -file root_ca.cer -keystore truststore.jks -storepass changeit -noprompt

    - name: Import Intermediate CA Certificate into Keystore
      run: |
        keytool -import -alias myintermediatecacert -file intermediate_ca.cer -keystore truststore.jks -storepass ${{secrets.JKS_STOREPASS}} -noprompt

    - name: List base signed dir 
      run: ls -al *

    - name: List workspace signed dir 
      run: ls -al ${{github.workspace}}/*
