name: Demo Commit GitHub Actions Workflow

on: [push] 

jobs:
  build:
    runs-on: ubuntu-latest # The type of runner that the job will run on
    defaults:
      run:
        working-directory: ./HelloWorld
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4 # Action to check out the repository's code

      - name: List src dir 
        run: ls -al src/com/example/helloworld/*

      - name: List base dir 
        run: ls -al 

      - name: Upload JAR 
        uses: actions/upload-artifact@v4
        with:
          name: HelloWorld.java
          path: ${{github.workspace}}/HelloWorld/out/artifacts/HelloWorld_java/HelloWorld.java
          retention-days: 1

      - name: List upload dir 
        run: ls -al  ${{github.workspace}}/HelloWorld/out/artifacts/HelloWorld_java/*

  sign:
    runs-on: ubuntu-latest # The type of runner that the job will run on
    needs: build 
    steps:

    - name: Download artifact from Build-Java
      uses: actions/download-artifact@v4
      with:
        name: HelloWorld.java

    - name: List workspace
      run: ls -al ${{github.workspace}}

    - name: SignServer Signing
      uses: Keyfactor/signserver-signing-action@v1.0.0
      with:
        endpoint: ${{secrets.SIGNSERVER_URL}} 
        file-path: ${{github.workspace}}/HelloWorld.java
        worker-name: OpenPGPSigner
        worker-type: OpenPGPSigner

  verify:
    runs-on: ubuntu-latest # The type of runner that the job will run on
    needs: sign 
    steps:

    - name: Decode Root CA Certificate
      env:
        ROOT_CERT_B64: ${{secrets.ROOT_CA_BASE64}} # Store your base64 encoded certificate in GitHub Secrets
      run: |
        echo "$ROOT_CERT_B64" | base64 --decode > root_ca.cer

    - name: Decode Intermediate CA Certificate
      env:
        INTERMEDIATE_CERT_B64: ${{secrets.INTERMEDIATE_CA_BASE64}} # Store your base64 encoded certificate in GitHub Secrets
      run: |
        echo "$INTERMEDIATE_CERT_B64" | base64 --decode > intermediate_ca.cer

    - name: Import Root CA Certificate into Keystore
      run: |
        keytool -import -alias myrootcacert -file root_ca.cer -keystore truststore.jks -storepass changeit -noprompt

    - name: Import Intermediate CA Certificate into Keystore
      run: |
        keytool -import -alias myintermediatecacert -file intermediate_ca.cer -keystore truststore.jks -storepass ${{secrets.JKS_STOREPASS}} -noprompt

    - name: Download Signed Java
      uses: actions/download-artifact@v4 
      with:
        name: signed-input.java

    - name: Download Signed Java
      uses: actions/download-artifact@v4 
      with:
        name: signed-input.asc

    - name: List base signed dir 
      run: ls -al *

    - name: List workspace signed dir 
      run: ls -al ${{github.workspace}}/*

    - name: Verify Signed Java
      run: |
        gpg --verify signed-input.asc signed-input.sig
